//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.07 at 10:43:44 AM CEST 
//


package xml.xhtml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *       form uses "Block" excluding form
 *       
 * 
 * <p>Java class for form.content complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="form.content">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{http://www.w3.org/1999/xhtml}block"/>
 *         &lt;group ref="{http://www.w3.org/1999/xhtml}misc"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "form.content", namespace = "http://www.w3.org/1999/xhtml", propOrder = {
    "pOrH1OrH2"
})
@XmlSeeAlso({
    Form.class
})
public class FormContent {

    @XmlElements({
        @XmlElement(name = "hr", namespace = "http://www.w3.org/1999/xhtml", type = Hr.class),
        @XmlElement(name = "ins", namespace = "http://www.w3.org/1999/xhtml", type = Ins.class),
        @XmlElement(name = "table", namespace = "http://www.w3.org/1999/xhtml", type = Table.class),
        @XmlElement(name = "blockquote", namespace = "http://www.w3.org/1999/xhtml", type = Blockquote.class),
        @XmlElement(name = "h3", namespace = "http://www.w3.org/1999/xhtml", type = H3 .class),
        @XmlElement(name = "ol", namespace = "http://www.w3.org/1999/xhtml", type = Ol.class),
        @XmlElement(name = "p", namespace = "http://www.w3.org/1999/xhtml", type = P.class),
        @XmlElement(name = "dl", namespace = "http://www.w3.org/1999/xhtml", type = Dl.class),
        @XmlElement(name = "noscript", namespace = "http://www.w3.org/1999/xhtml", type = Noscript.class),
        @XmlElement(name = "h6", namespace = "http://www.w3.org/1999/xhtml", type = H6 .class),
        @XmlElement(name = "pre", namespace = "http://www.w3.org/1999/xhtml", type = Pre.class),
        @XmlElement(name = "div", namespace = "http://www.w3.org/1999/xhtml", type = Div.class),
        @XmlElement(name = "h5", namespace = "http://www.w3.org/1999/xhtml", type = H5 .class),
        @XmlElement(name = "address", namespace = "http://www.w3.org/1999/xhtml", type = Address.class),
        @XmlElement(name = "del", namespace = "http://www.w3.org/1999/xhtml", type = Del.class),
        @XmlElement(name = "h1", namespace = "http://www.w3.org/1999/xhtml", type = H1 .class),
        @XmlElement(name = "fieldset", namespace = "http://www.w3.org/1999/xhtml", type = Fieldset.class),
        @XmlElement(name = "h4", namespace = "http://www.w3.org/1999/xhtml", type = H4 .class),
        @XmlElement(name = "script", namespace = "http://www.w3.org/1999/xhtml", type = Script.class),
        @XmlElement(name = "ul", namespace = "http://www.w3.org/1999/xhtml", type = Ul.class),
        @XmlElement(name = "h2", namespace = "http://www.w3.org/1999/xhtml", type = H2 .class)
    })
    protected List<java.lang.Object> pOrH1OrH2;

    /**
     * Gets the value of the pOrH1OrH2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pOrH1OrH2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPOrH1OrH2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Hr }
     * {@link Ins }
     * {@link Table }
     * {@link Blockquote }
     * {@link H3 }
     * {@link Ol }
     * {@link P }
     * {@link Dl }
     * {@link Noscript }
     * {@link H6 }
     * {@link Pre }
     * {@link Div }
     * {@link H5 }
     * {@link Address }
     * {@link Del }
     * {@link H1 }
     * {@link Fieldset }
     * {@link H4 }
     * {@link Script }
     * {@link Ul }
     * {@link H2 }
     * 
     * 
     */
    public List<java.lang.Object> getPOrH1OrH2() {
        if (pOrH1OrH2 == null) {
            pOrH1OrH2 = new ArrayList<java.lang.Object>();
        }
        return this.pOrH1OrH2;
    }

}
