//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.04 at 12:16:10 PM CEST 
//


package xml.xsd.v16;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				L'elemento anagrafica adesso è obbligatorio.
 * 			
 * 
 * <p>Java class for anagraficaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="anagraficaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="data-censimento" type="{}annoSecoloType" minOccurs="0"/>
 *         &lt;element name="data-aggiornamento" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="fonte" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="descrizione" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="nomi">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attuale">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="precedenti" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="precedente" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="alternativi" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="alternativo" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="codici">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="isil" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="acnp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="rism" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="sbn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="cei" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="cmbs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="indirizzo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="via" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="cap" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="frazione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="comune">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[0-9]{6}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="provincia" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[0-9]{3}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="regione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="stato" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[a-zA-Z]{2}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="coordinate" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="latitudine" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                           &lt;attribute name="longitudine" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="contatti" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="telefonici" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="telefonico" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="prefisso" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="numero" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="tipo" use="required">
 *                                       &lt;simpleType>
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                           &lt;enumeration value="fax"/>
 *                                           &lt;enumeration value="telefono"/>
 *                                         &lt;/restriction>
 *                                       &lt;/simpleType>
 *                                     &lt;/attribute>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="altri" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="altro" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="valore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="tipo" use="required">
 *                                       &lt;simpleType>
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                           &lt;enumeration value="e-mail"/>
 *                                           &lt;enumeration value="telex"/>
 *                                           &lt;enumeration value="url"/>
 *                                         &lt;/restriction>
 *                                       &lt;/simpleType>
 *                                     &lt;/attribute>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="edificio" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="denominazione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="monumentale" type="{}siNoType" minOccurs="0"/>
 *                   &lt;element name="appositamente-costruito" type="{}siNoType" minOccurs="0"/>
 *                   &lt;element name="data-costruzione" type="{}annoSecoloType" minOccurs="0"/>
 *                   &lt;element name="immagini" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="immagine" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="didascalia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="istituzione" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="data-istituzione" type="{}annoSecoloType" minOccurs="0"/>
 *                   &lt;element name="data-fondazione" type="{}annoSecoloType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "anagraficaType", propOrder = {
    "dataCensimento",
    "dataAggiornamento",
    "fonte",
    "nomi",
    "codici",
    "indirizzo",
    "contatti",
    "edificio",
    "istituzione"
})
public class AnagraficaType {

    @XmlElement(name = "data-censimento")
    protected AnnoSecoloType dataCensimento;
    @XmlElement(name = "data-aggiornamento")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataAggiornamento;
    protected AnagraficaType.Fonte fonte;
    @XmlElement(required = true)
    protected AnagraficaType.Nomi nomi;
    @XmlElement(required = true)
    protected AnagraficaType.Codici codici;
    protected AnagraficaType.Indirizzo indirizzo;
    protected AnagraficaType.Contatti contatti;
    protected AnagraficaType.Edificio edificio;
    protected AnagraficaType.Istituzione istituzione;

    /**
     * Gets the value of the dataCensimento property.
     * 
     * @return
     *     possible object is
     *     {@link AnnoSecoloType }
     *     
     */
    public AnnoSecoloType getDataCensimento() {
        return dataCensimento;
    }

    /**
     * Sets the value of the dataCensimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnoSecoloType }
     *     
     */
    public void setDataCensimento(AnnoSecoloType value) {
        this.dataCensimento = value;
    }

    /**
     * Gets the value of the dataAggiornamento property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataAggiornamento() {
        return dataAggiornamento;
    }

    /**
     * Sets the value of the dataAggiornamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataAggiornamento(XMLGregorianCalendar value) {
        this.dataAggiornamento = value;
    }

    /**
     * Gets the value of the fonte property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaType.Fonte }
     *     
     */
    public AnagraficaType.Fonte getFonte() {
        return fonte;
    }

    /**
     * Sets the value of the fonte property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaType.Fonte }
     *     
     */
    public void setFonte(AnagraficaType.Fonte value) {
        this.fonte = value;
    }

    /**
     * Gets the value of the nomi property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaType.Nomi }
     *     
     */
    public AnagraficaType.Nomi getNomi() {
        return nomi;
    }

    /**
     * Sets the value of the nomi property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaType.Nomi }
     *     
     */
    public void setNomi(AnagraficaType.Nomi value) {
        this.nomi = value;
    }

    /**
     * Gets the value of the codici property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaType.Codici }
     *     
     */
    public AnagraficaType.Codici getCodici() {
        return codici;
    }

    /**
     * Sets the value of the codici property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaType.Codici }
     *     
     */
    public void setCodici(AnagraficaType.Codici value) {
        this.codici = value;
    }

    /**
     * Gets the value of the indirizzo property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaType.Indirizzo }
     *     
     */
    public AnagraficaType.Indirizzo getIndirizzo() {
        return indirizzo;
    }

    /**
     * Sets the value of the indirizzo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaType.Indirizzo }
     *     
     */
    public void setIndirizzo(AnagraficaType.Indirizzo value) {
        this.indirizzo = value;
    }

    /**
     * Gets the value of the contatti property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaType.Contatti }
     *     
     */
    public AnagraficaType.Contatti getContatti() {
        return contatti;
    }

    /**
     * Sets the value of the contatti property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaType.Contatti }
     *     
     */
    public void setContatti(AnagraficaType.Contatti value) {
        this.contatti = value;
    }

    /**
     * Gets the value of the edificio property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaType.Edificio }
     *     
     */
    public AnagraficaType.Edificio getEdificio() {
        return edificio;
    }

    /**
     * Sets the value of the edificio property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaType.Edificio }
     *     
     */
    public void setEdificio(AnagraficaType.Edificio value) {
        this.edificio = value;
    }

    /**
     * Gets the value of the istituzione property.
     * 
     * @return
     *     possible object is
     *     {@link AnagraficaType.Istituzione }
     *     
     */
    public AnagraficaType.Istituzione getIstituzione() {
        return istituzione;
    }

    /**
     * Sets the value of the istituzione property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnagraficaType.Istituzione }
     *     
     */
    public void setIstituzione(AnagraficaType.Istituzione value) {
        this.istituzione = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="isil" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="acnp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="rism" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="sbn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="cei" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="cmbs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "isil",
        "acnp",
        "rism",
        "sbn",
        "cei",
        "cmbs"
    })
    public static class Codici {

        @XmlElement(required = true)
        protected String isil;
        protected String acnp;
        protected String rism;
        protected String sbn;
        protected String cei;
        protected String cmbs;

        /**
         * Gets the value of the isil property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsil() {
            return isil;
        }

        /**
         * Sets the value of the isil property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsil(String value) {
            this.isil = value;
        }

        /**
         * Gets the value of the acnp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAcnp() {
            return acnp;
        }

        /**
         * Sets the value of the acnp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAcnp(String value) {
            this.acnp = value;
        }

        /**
         * Gets the value of the rism property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRism() {
            return rism;
        }

        /**
         * Sets the value of the rism property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRism(String value) {
            this.rism = value;
        }

        /**
         * Gets the value of the sbn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSbn() {
            return sbn;
        }

        /**
         * Sets the value of the sbn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSbn(String value) {
            this.sbn = value;
        }

        /**
         * Gets the value of the cei property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCei() {
            return cei;
        }

        /**
         * Sets the value of the cei property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCei(String value) {
            this.cei = value;
        }

        /**
         * Gets the value of the cmbs property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCmbs() {
            return cmbs;
        }

        /**
         * Sets the value of the cmbs property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCmbs(String value) {
            this.cmbs = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="telefonici" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="telefonico" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="prefisso" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="numero" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="tipo" use="required">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="fax"/>
     *                                 &lt;enumeration value="telefono"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="altri" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="altro" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="valore" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="tipo" use="required">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="e-mail"/>
     *                                 &lt;enumeration value="telex"/>
     *                                 &lt;enumeration value="url"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "telefonici",
        "altri"
    })
    public static class Contatti {

        protected AnagraficaType.Contatti.Telefonici telefonici;
        protected AnagraficaType.Contatti.Altri altri;

        /**
         * Gets the value of the telefonici property.
         * 
         * @return
         *     possible object is
         *     {@link AnagraficaType.Contatti.Telefonici }
         *     
         */
        public AnagraficaType.Contatti.Telefonici getTelefonici() {
            return telefonici;
        }

        /**
         * Sets the value of the telefonici property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnagraficaType.Contatti.Telefonici }
         *     
         */
        public void setTelefonici(AnagraficaType.Contatti.Telefonici value) {
            this.telefonici = value;
        }

        /**
         * Gets the value of the altri property.
         * 
         * @return
         *     possible object is
         *     {@link AnagraficaType.Contatti.Altri }
         *     
         */
        public AnagraficaType.Contatti.Altri getAltri() {
            return altri;
        }

        /**
         * Sets the value of the altri property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnagraficaType.Contatti.Altri }
         *     
         */
        public void setAltri(AnagraficaType.Contatti.Altri value) {
            this.altri = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="altro" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="valore" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="tipo" use="required">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="e-mail"/>
         *                       &lt;enumeration value="telex"/>
         *                       &lt;enumeration value="url"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "altro"
        })
        public static class Altri {

            protected List<AnagraficaType.Contatti.Altri.Altro> altro;

            /**
             * Gets the value of the altro property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the altro property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAltro().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AnagraficaType.Contatti.Altri.Altro }
             * 
             * 
             */
            public List<AnagraficaType.Contatti.Altri.Altro> getAltro() {
                if (altro == null) {
                    altro = new ArrayList<AnagraficaType.Contatti.Altri.Altro>();
                }
                return this.altro;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="valore" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *       &lt;attribute name="tipo" use="required">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="e-mail"/>
             *             &lt;enumeration value="telex"/>
             *             &lt;enumeration value="url"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "valore",
                "note"
            })
            public static class Altro {

                @XmlElement(required = true)
                protected String valore;
                protected String note;
                @XmlAttribute(required = true)
                protected String tipo;

                /**
                 * Gets the value of the valore property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValore() {
                    return valore;
                }

                /**
                 * Sets the value of the valore property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValore(String value) {
                    this.valore = value;
                }

                /**
                 * Gets the value of the note property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNote() {
                    return note;
                }

                /**
                 * Sets the value of the note property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNote(String value) {
                    this.note = value;
                }

                /**
                 * Gets the value of the tipo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTipo() {
                    return tipo;
                }

                /**
                 * Sets the value of the tipo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTipo(String value) {
                    this.tipo = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="telefonico" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="prefisso" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="numero" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="tipo" use="required">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="fax"/>
         *                       &lt;enumeration value="telefono"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "telefonico"
        })
        public static class Telefonici {

            protected List<AnagraficaType.Contatti.Telefonici.Telefonico> telefonico;

            /**
             * Gets the value of the telefonico property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the telefonico property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTelefonico().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AnagraficaType.Contatti.Telefonici.Telefonico }
             * 
             * 
             */
            public List<AnagraficaType.Contatti.Telefonici.Telefonico> getTelefonico() {
                if (telefonico == null) {
                    telefonico = new ArrayList<AnagraficaType.Contatti.Telefonici.Telefonico>();
                }
                return this.telefonico;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="prefisso" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="numero" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *       &lt;attribute name="tipo" use="required">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="fax"/>
             *             &lt;enumeration value="telefono"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "prefisso",
                "numero",
                "note"
            })
            public static class Telefonico {

                @XmlElement(required = true)
                protected String prefisso;
                @XmlElement(required = true)
                protected String numero;
                protected String note;
                @XmlAttribute(required = true)
                protected String tipo;

                /**
                 * Gets the value of the prefisso property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPrefisso() {
                    return prefisso;
                }

                /**
                 * Sets the value of the prefisso property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPrefisso(String value) {
                    this.prefisso = value;
                }

                /**
                 * Gets the value of the numero property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNumero() {
                    return numero;
                }

                /**
                 * Sets the value of the numero property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNumero(String value) {
                    this.numero = value;
                }

                /**
                 * Gets the value of the note property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNote() {
                    return note;
                }

                /**
                 * Sets the value of the note property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNote(String value) {
                    this.note = value;
                }

                /**
                 * Gets the value of the tipo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTipo() {
                    return tipo;
                }

                /**
                 * Sets the value of the tipo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTipo(String value) {
                    this.tipo = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="denominazione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="monumentale" type="{}siNoType" minOccurs="0"/>
     *         &lt;element name="appositamente-costruito" type="{}siNoType" minOccurs="0"/>
     *         &lt;element name="data-costruzione" type="{}annoSecoloType" minOccurs="0"/>
     *         &lt;element name="immagini" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="immagine" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="didascalia" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "denominazione",
        "monumentale",
        "appositamenteCostruito",
        "dataCostruzione",
        "immagini"
    })
    public static class Edificio {

        protected String denominazione;
        protected SiNoType monumentale;
        @XmlElement(name = "appositamente-costruito")
        protected SiNoType appositamenteCostruito;
        @XmlElement(name = "data-costruzione")
        protected AnnoSecoloType dataCostruzione;
        protected AnagraficaType.Edificio.Immagini immagini;

        /**
         * Gets the value of the denominazione property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDenominazione() {
            return denominazione;
        }

        /**
         * Sets the value of the denominazione property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDenominazione(String value) {
            this.denominazione = value;
        }

        /**
         * Gets the value of the monumentale property.
         * 
         * @return
         *     possible object is
         *     {@link SiNoType }
         *     
         */
        public SiNoType getMonumentale() {
            return monumentale;
        }

        /**
         * Sets the value of the monumentale property.
         * 
         * @param value
         *     allowed object is
         *     {@link SiNoType }
         *     
         */
        public void setMonumentale(SiNoType value) {
            this.monumentale = value;
        }

        /**
         * Gets the value of the appositamenteCostruito property.
         * 
         * @return
         *     possible object is
         *     {@link SiNoType }
         *     
         */
        public SiNoType getAppositamenteCostruito() {
            return appositamenteCostruito;
        }

        /**
         * Sets the value of the appositamenteCostruito property.
         * 
         * @param value
         *     allowed object is
         *     {@link SiNoType }
         *     
         */
        public void setAppositamenteCostruito(SiNoType value) {
            this.appositamenteCostruito = value;
        }

        /**
         * Gets the value of the dataCostruzione property.
         * 
         * @return
         *     possible object is
         *     {@link AnnoSecoloType }
         *     
         */
        public AnnoSecoloType getDataCostruzione() {
            return dataCostruzione;
        }

        /**
         * Sets the value of the dataCostruzione property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnnoSecoloType }
         *     
         */
        public void setDataCostruzione(AnnoSecoloType value) {
            this.dataCostruzione = value;
        }

        /**
         * Gets the value of the immagini property.
         * 
         * @return
         *     possible object is
         *     {@link AnagraficaType.Edificio.Immagini }
         *     
         */
        public AnagraficaType.Edificio.Immagini getImmagini() {
            return immagini;
        }

        /**
         * Sets the value of the immagini property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnagraficaType.Edificio.Immagini }
         *     
         */
        public void setImmagini(AnagraficaType.Edificio.Immagini value) {
            this.immagini = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="immagine" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="didascalia" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "immagine"
        })
        public static class Immagini {

            protected List<AnagraficaType.Edificio.Immagini.Immagine> immagine;

            /**
             * Gets the value of the immagine property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the immagine property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getImmagine().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AnagraficaType.Edificio.Immagini.Immagine }
             * 
             * 
             */
            public List<AnagraficaType.Edificio.Immagini.Immagine> getImmagine() {
                if (immagine == null) {
                    immagine = new ArrayList<AnagraficaType.Edificio.Immagini.Immagine>();
                }
                return this.immagine;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="didascalia" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "url",
                "didascalia"
            })
            public static class Immagine {

                @XmlElement(required = true)
                protected String url;
                @XmlElement(required = true)
                protected String didascalia;

                /**
                 * Gets the value of the url property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUrl() {
                    return url;
                }

                /**
                 * Sets the value of the url property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUrl(String value) {
                    this.url = value;
                }

                /**
                 * Gets the value of the didascalia property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDidascalia() {
                    return didascalia;
                }

                /**
                 * Sets the value of the didascalia property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDidascalia(String value) {
                    this.didascalia = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="descrizione" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "descrizione",
        "url"
    })
    public static class Fonte {

        @XmlElement(required = true)
        protected String descrizione;
        @XmlElement(required = true)
        protected String url;

        /**
         * Gets the value of the descrizione property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescrizione() {
            return descrizione;
        }

        /**
         * Sets the value of the descrizione property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescrizione(String value) {
            this.descrizione = value;
        }

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrl() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrl(String value) {
            this.url = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="via" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="cap" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="frazione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="comune">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[0-9]{6}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="provincia" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[0-9]{3}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="regione" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="stato" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[a-zA-Z]{2}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="coordinate" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="latitudine" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                 &lt;attribute name="longitudine" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "via",
        "cap",
        "frazione",
        "comune",
        "provincia",
        "regione",
        "stato",
        "coordinate"
    })
    public static class Indirizzo {

        protected String via;
        protected String cap;
        protected String frazione;
        @XmlElement(required = true)
        protected String comune;
        protected String provincia;
        protected String regione;
        protected String stato;
        protected AnagraficaType.Indirizzo.Coordinate coordinate;

        /**
         * Gets the value of the via property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVia() {
            return via;
        }

        /**
         * Sets the value of the via property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVia(String value) {
            this.via = value;
        }

        /**
         * Gets the value of the cap property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCap() {
            return cap;
        }

        /**
         * Sets the value of the cap property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCap(String value) {
            this.cap = value;
        }

        /**
         * Gets the value of the frazione property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFrazione() {
            return frazione;
        }

        /**
         * Sets the value of the frazione property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFrazione(String value) {
            this.frazione = value;
        }

        /**
         * Gets the value of the comune property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComune() {
            return comune;
        }

        /**
         * Sets the value of the comune property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComune(String value) {
            this.comune = value;
        }

        /**
         * Gets the value of the provincia property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProvincia() {
            return provincia;
        }

        /**
         * Sets the value of the provincia property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProvincia(String value) {
            this.provincia = value;
        }

        /**
         * Gets the value of the regione property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegione() {
            return regione;
        }

        /**
         * Sets the value of the regione property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegione(String value) {
            this.regione = value;
        }

        /**
         * Gets the value of the stato property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStato() {
            return stato;
        }

        /**
         * Sets the value of the stato property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStato(String value) {
            this.stato = value;
        }

        /**
         * Gets the value of the coordinate property.
         * 
         * @return
         *     possible object is
         *     {@link AnagraficaType.Indirizzo.Coordinate }
         *     
         */
        public AnagraficaType.Indirizzo.Coordinate getCoordinate() {
            return coordinate;
        }

        /**
         * Sets the value of the coordinate property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnagraficaType.Indirizzo.Coordinate }
         *     
         */
        public void setCoordinate(AnagraficaType.Indirizzo.Coordinate value) {
            this.coordinate = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="latitudine" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *       &lt;attribute name="longitudine" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Coordinate {

            @XmlAttribute(required = true)
            protected double latitudine;
            @XmlAttribute(required = true)
            protected double longitudine;

            /**
             * Gets the value of the latitudine property.
             * 
             */
            public double getLatitudine() {
                return latitudine;
            }

            /**
             * Sets the value of the latitudine property.
             * 
             */
            public void setLatitudine(double value) {
                this.latitudine = value;
            }

            /**
             * Gets the value of the longitudine property.
             * 
             */
            public double getLongitudine() {
                return longitudine;
            }

            /**
             * Sets the value of the longitudine property.
             * 
             */
            public void setLongitudine(double value) {
                this.longitudine = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="data-istituzione" type="{}annoSecoloType" minOccurs="0"/>
     *         &lt;element name="data-fondazione" type="{}annoSecoloType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataIstituzione",
        "dataFondazione"
    })
    public static class Istituzione {

        @XmlElement(name = "data-istituzione")
        protected AnnoSecoloType dataIstituzione;
        @XmlElement(name = "data-fondazione")
        protected AnnoSecoloType dataFondazione;

        /**
         * Gets the value of the dataIstituzione property.
         * 
         * @return
         *     possible object is
         *     {@link AnnoSecoloType }
         *     
         */
        public AnnoSecoloType getDataIstituzione() {
            return dataIstituzione;
        }

        /**
         * Sets the value of the dataIstituzione property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnnoSecoloType }
         *     
         */
        public void setDataIstituzione(AnnoSecoloType value) {
            this.dataIstituzione = value;
        }

        /**
         * Gets the value of the dataFondazione property.
         * 
         * @return
         *     possible object is
         *     {@link AnnoSecoloType }
         *     
         */
        public AnnoSecoloType getDataFondazione() {
            return dataFondazione;
        }

        /**
         * Sets the value of the dataFondazione property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnnoSecoloType }
         *     
         */
        public void setDataFondazione(AnnoSecoloType value) {
            this.dataFondazione = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attuale">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="precedenti" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="precedente" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="alternativi" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="alternativo" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attuale",
        "precedenti",
        "alternativi"
    })
    public static class Nomi {

        @XmlElement(required = true)
        protected String attuale;
        protected AnagraficaType.Nomi.Precedenti precedenti;
        protected AnagraficaType.Nomi.Alternativi alternativi;

        /**
         * Gets the value of the attuale property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttuale() {
            return attuale;
        }

        /**
         * Sets the value of the attuale property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttuale(String value) {
            this.attuale = value;
        }

        /**
         * Gets the value of the precedenti property.
         * 
         * @return
         *     possible object is
         *     {@link AnagraficaType.Nomi.Precedenti }
         *     
         */
        public AnagraficaType.Nomi.Precedenti getPrecedenti() {
            return precedenti;
        }

        /**
         * Sets the value of the precedenti property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnagraficaType.Nomi.Precedenti }
         *     
         */
        public void setPrecedenti(AnagraficaType.Nomi.Precedenti value) {
            this.precedenti = value;
        }

        /**
         * Gets the value of the alternativi property.
         * 
         * @return
         *     possible object is
         *     {@link AnagraficaType.Nomi.Alternativi }
         *     
         */
        public AnagraficaType.Nomi.Alternativi getAlternativi() {
            return alternativi;
        }

        /**
         * Sets the value of the alternativi property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnagraficaType.Nomi.Alternativi }
         *     
         */
        public void setAlternativi(AnagraficaType.Nomi.Alternativi value) {
            this.alternativi = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="alternativo" maxOccurs="unbounded" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "alternativo"
        })
        public static class Alternativi {

            protected List<String> alternativo;

            /**
             * Gets the value of the alternativo property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the alternativo property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAlternativo().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getAlternativo() {
                if (alternativo == null) {
                    alternativo = new ArrayList<String>();
                }
                return this.alternativo;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="precedente" maxOccurs="unbounded" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "precedente"
        })
        public static class Precedenti {

            protected List<String> precedente;

            /**
             * Gets the value of the precedente property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the precedente property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPrecedente().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getPrecedente() {
                if (precedente == null) {
                    precedente = new ArrayList<String>();
                }
                return this.precedente;
            }

        }

    }

}
