//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.04 at 12:16:10 PM CEST 
//


package xml.xsd.v16;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="data-export" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="biblioteca" type="{}bibliotecaType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataExport",
    "biblioteca"
})
@XmlRootElement(name = "biblioteche")
public class Biblioteche {

    @XmlElement(name = "data-export", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataExport;
    @XmlElement(required = true)
    protected List<BibliotecaType> biblioteca;

    /**
     * Gets the value of the dataExport property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataExport() {
        return dataExport;
    }

    /**
     * Sets the value of the dataExport property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataExport(XMLGregorianCalendar value) {
        this.dataExport = value;
    }

    /**
     * Gets the value of the biblioteca property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the biblioteca property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBiblioteca().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BibliotecaType }
     * 
     * 
     */
    public List<BibliotecaType> getBiblioteca() {
        if (biblioteca == null) {
            biblioteca = new ArrayList<BibliotecaType>();
        }
        return this.biblioteca;
    }

}
