//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.04 at 12:16:10 PM CEST 
//


package xml.xsd.v16;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Notare come tale tipo di elemento costituisce la base
 * 				per il "catalogoSpecialeType".
 * 			
 * 
 * <p>Java class for catalogoSpecialeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="catalogoSpecialeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="materiali" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="materiale" type="{}materialeCataloghiType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "catalogoSpecialeType", propOrder = {
    "nome",
    "materiali"
})
@XmlSeeAlso({
    CatalogoCollettivoType.class
})
public class CatalogoSpecialeType {

    protected String nome;
    protected CatalogoSpecialeType.Materiali materiali;

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNome(String value) {
        this.nome = value;
    }

    /**
     * Gets the value of the materiali property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogoSpecialeType.Materiali }
     *     
     */
    public CatalogoSpecialeType.Materiali getMateriali() {
        return materiali;
    }

    /**
     * Sets the value of the materiali property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogoSpecialeType.Materiali }
     *     
     */
    public void setMateriali(CatalogoSpecialeType.Materiali value) {
        this.materiali = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="materiale" type="{}materialeCataloghiType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "materiale"
    })
    public static class Materiali {

        protected List<MaterialeCataloghiType> materiale;

        /**
         * Gets the value of the materiale property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the materiale property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMateriale().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MaterialeCataloghiType }
         * 
         * 
         */
        public List<MaterialeCataloghiType> getMateriale() {
            if (materiale == null) {
                materiale = new ArrayList<MaterialeCataloghiType>();
            }
            return this.materiale;
        }

    }

}
