//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.04 at 12:16:10 PM CEST 
//


package xml.xsd.v16;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xml.xsd.v16 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xml.xsd.v16
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AnagraficaType }
     * 
     */
    public AnagraficaType createAnagraficaType() {
        return new AnagraficaType();
    }

    /**
     * Create an instance of {@link ServiziType.Prestito.Interbibliotecario }
     * 
     */
    public ServiziType.Prestito.Interbibliotecario createServiziTypePrestitoInterbibliotecario() {
        return new ServiziType.Prestito.Interbibliotecario();
    }

    /**
     * Create an instance of {@link ServiziType.Sistemi }
     * 
     */
    public ServiziType.Sistemi createServiziTypeSistemi() {
        return new ServiziType.Sistemi();
    }

    /**
     * Create an instance of {@link BibliotecaType }
     * 
     */
    public BibliotecaType createBibliotecaType() {
        return new BibliotecaType();
    }

    /**
     * Create an instance of {@link AnagraficaType.Codici }
     * 
     */
    public AnagraficaType.Codici createAnagraficaTypeCodici() {
        return new AnagraficaType.Codici();
    }

    /**
     * Create an instance of {@link AnagraficaType.Indirizzo }
     * 
     */
    public AnagraficaType.Indirizzo createAnagraficaTypeIndirizzo() {
        return new AnagraficaType.Indirizzo();
    }

    /**
     * Create an instance of {@link AnagraficaType.Edificio.Immagini }
     * 
     */
    public AnagraficaType.Edificio.Immagini createAnagraficaTypeEdificioImmagini() {
        return new AnagraficaType.Edificio.Immagini();
    }

    /**
     * Create an instance of {@link BibliotecaType.Specializzazioni }
     * 
     */
    public BibliotecaType.Specializzazioni createBibliotecaTypeSpecializzazioni() {
        return new BibliotecaType.Specializzazioni();
    }

    /**
     * Create an instance of {@link AnagraficaType.Nomi.Alternativi }
     * 
     */
    public AnagraficaType.Nomi.Alternativi createAnagraficaTypeNomiAlternativi() {
        return new AnagraficaType.Nomi.Alternativi();
    }

    /**
     * Create an instance of {@link AnagraficaType.Edificio.Immagini.Immagine }
     * 
     */
    public AnagraficaType.Edificio.Immagini.Immagine createAnagraficaTypeEdificioImmaginiImmagine() {
        return new AnagraficaType.Edificio.Immagini.Immagine();
    }

    /**
     * Create an instance of {@link AnnoSecoloType }
     * 
     */
    public AnnoSecoloType createAnnoSecoloType() {
        return new AnnoSecoloType();
    }

    /**
     * Create an instance of {@link CataloghiType.CataloghiSpeciali }
     * 
     */
    public CataloghiType.CataloghiSpeciali createCataloghiTypeCataloghiSpeciali() {
        return new CataloghiType.CataloghiSpeciali();
    }

    /**
     * Create an instance of {@link AmministrativaType.Strutture.Postazioni }
     * 
     */
    public AmministrativaType.Strutture.Postazioni createAmministrativaTypeStrutturePostazioni() {
        return new AmministrativaType.Strutture.Postazioni();
    }

    /**
     * Create an instance of {@link ServiziType.Orario }
     * 
     */
    public ServiziType.Orario createServiziTypeOrario() {
        return new ServiziType.Orario();
    }

    /**
     * Create an instance of {@link ServiziType.Internet }
     * 
     */
    public ServiziType.Internet createServiziTypeInternet() {
        return new ServiziType.Internet();
    }

    /**
     * Create an instance of {@link CatalogoType.Forme }
     * 
     */
    public CatalogoType.Forme createCatalogoTypeForme() {
        return new CatalogoType.Forme();
    }

    /**
     * Create an instance of {@link ServiziType.SezioniSpeciali }
     * 
     */
    public ServiziType.SezioniSpeciali createServiziTypeSezioniSpeciali() {
        return new ServiziType.SezioniSpeciali();
    }

    /**
     * Create an instance of {@link ServiziType.Accesso.DestinazioniSociali }
     * 
     */
    public ServiziType.Accesso.DestinazioniSociali createServiziTypeAccessoDestinazioniSociali() {
        return new ServiziType.Accesso.DestinazioniSociali();
    }

    /**
     * Create an instance of {@link MaterialeCataloghiType.Copertura }
     * 
     */
    public MaterialeCataloghiType.Copertura createMaterialeCataloghiTypeCopertura() {
        return new MaterialeCataloghiType.Copertura();
    }

    /**
     * Create an instance of {@link CatalogoType }
     * 
     */
    public CatalogoType createCatalogoType() {
        return new CatalogoType();
    }

    /**
     * Create an instance of {@link AmministrativaType.DepositiLegali }
     * 
     */
    public AmministrativaType.DepositiLegali createAmministrativaTypeDepositiLegali() {
        return new AmministrativaType.DepositiLegali();
    }

    /**
     * Create an instance of {@link AnagraficaType.Contatti.Telefonici.Telefonico }
     * 
     */
    public AnagraficaType.Contatti.Telefonici.Telefonico createAnagraficaTypeContattiTelefoniciTelefonico() {
        return new AnagraficaType.Contatti.Telefonici.Telefonico();
    }

    /**
     * Create an instance of {@link PatrimonioType }
     * 
     */
    public PatrimonioType createPatrimonioType() {
        return new PatrimonioType();
    }

    /**
     * Create an instance of {@link CatalogoCollettivoType.Zona }
     * 
     */
    public CatalogoCollettivoType.Zona createCatalogoCollettivoTypeZona() {
        return new CatalogoCollettivoType.Zona();
    }

    /**
     * Create an instance of {@link AnagraficaType.Contatti.Altri.Altro }
     * 
     */
    public AnagraficaType.Contatti.Altri.Altro createAnagraficaTypeContattiAltriAltro() {
        return new AnagraficaType.Contatti.Altri.Altro();
    }

    /**
     * Create an instance of {@link FondoAnticoType }
     * 
     */
    public FondoAnticoType createFondoAnticoType() {
        return new FondoAnticoType();
    }

    /**
     * Create an instance of {@link InfCarType }
     * 
     */
    public InfCarType createInfCarType() {
        return new InfCarType();
    }

    /**
     * Create an instance of {@link MaterialeCataloghiType }
     * 
     */
    public MaterialeCataloghiType createMaterialeCataloghiType() {
        return new MaterialeCataloghiType();
    }

    /**
     * Create an instance of {@link AnagraficaType.Contatti }
     * 
     */
    public AnagraficaType.Contatti createAnagraficaTypeContatti() {
        return new AnagraficaType.Contatti();
    }

    /**
     * Create an instance of {@link AmministrativaType.DepositiLegali.DepositoLegale }
     * 
     */
    public AmministrativaType.DepositiLegali.DepositoLegale createAmministrativaTypeDepositiLegaliDepositoLegale() {
        return new AmministrativaType.DepositiLegali.DepositoLegale();
    }

    /**
     * Create an instance of {@link AmministrativaType.Utenti }
     * 
     */
    public AmministrativaType.Utenti createAmministrativaTypeUtenti() {
        return new AmministrativaType.Utenti();
    }

    /**
     * Create an instance of {@link OrarioType }
     * 
     */
    public OrarioType createOrarioType() {
        return new OrarioType();
    }

    /**
     * Create an instance of {@link AmministrativaType.Personale }
     * 
     */
    public AmministrativaType.Personale createAmministrativaTypePersonale() {
        return new AmministrativaType.Personale();
    }

    /**
     * Create an instance of {@link CataloghiType.CataloghiCollettivi }
     * 
     */
    public CataloghiType.CataloghiCollettivi createCataloghiTypeCataloghiCollettivi() {
        return new CataloghiType.CataloghiCollettivi();
    }

    /**
     * Create an instance of {@link CataloghiType }
     * 
     */
    public CataloghiType createCataloghiType() {
        return new CataloghiType();
    }

    /**
     * Create an instance of {@link OrarioType.Orario }
     * 
     */
    public OrarioType.Orario createOrarioTypeOrario() {
        return new OrarioType.Orario();
    }

    /**
     * Create an instance of {@link VolumeType }
     * 
     */
    public VolumeType createVolumeType() {
        return new VolumeType();
    }

    /**
     * Create an instance of {@link ServiziType.Prestito.Locale.MaterialiEsclusi }
     * 
     */
    public ServiziType.Prestito.Locale.MaterialiEsclusi createServiziTypePrestitoLocaleMaterialiEsclusi() {
        return new ServiziType.Prestito.Locale.MaterialiEsclusi();
    }

    /**
     * Create an instance of {@link ServiziType.Accesso.ModalitaAccesso }
     * 
     */
    public ServiziType.Accesso.ModalitaAccesso createServiziTypeAccessoModalitaAccesso() {
        return new ServiziType.Accesso.ModalitaAccesso();
    }

    /**
     * Create an instance of {@link ServiziType.Prestito.Locale }
     * 
     */
    public ServiziType.Prestito.Locale createServiziTypePrestitoLocale() {
        return new ServiziType.Prestito.Locale();
    }

    /**
     * Create an instance of {@link AnagraficaType.Contatti.Telefonici }
     * 
     */
    public AnagraficaType.Contatti.Telefonici createAnagraficaTypeContattiTelefonici() {
        return new AnagraficaType.Contatti.Telefonici();
    }

    /**
     * Create an instance of {@link AmministrativaType }
     * 
     */
    public AmministrativaType createAmministrativaType() {
        return new AmministrativaType();
    }

    /**
     * Create an instance of {@link FondoSpecialeType }
     * 
     */
    public FondoSpecialeType createFondoSpecialeType() {
        return new FondoSpecialeType();
    }

    /**
     * Create an instance of {@link AmministrativaType.Bilancio }
     * 
     */
    public AmministrativaType.Bilancio createAmministrativaTypeBilancio() {
        return new AmministrativaType.Bilancio();
    }

    /**
     * Create an instance of {@link AmministrativaType.Regolamento }
     * 
     */
    public AmministrativaType.Regolamento createAmministrativaTypeRegolamento() {
        return new AmministrativaType.Regolamento();
    }

    /**
     * Create an instance of {@link ServiziType.Orario.Variazione }
     * 
     */
    public ServiziType.Orario.Variazione createServiziTypeOrarioVariazione() {
        return new ServiziType.Orario.Variazione();
    }

    /**
     * Create an instance of {@link ServiziType.Prestito.MaterialiEsclusiLocale }
     * 
     */
    public ServiziType.Prestito.MaterialiEsclusiLocale createServiziTypePrestitoMaterialiEsclusiLocale() {
        return new ServiziType.Prestito.MaterialiEsclusiLocale();
    }

    /**
     * Create an instance of {@link ServiziType.Riproduzioni }
     * 
     */
    public ServiziType.Riproduzioni createServiziTypeRiproduzioni() {
        return new ServiziType.Riproduzioni();
    }

    /**
     * Create an instance of {@link ServiziType.Accesso.DestinazioniSociali.Destinazione }
     * 
     */
    public ServiziType.Accesso.DestinazioniSociali.Destinazione createServiziTypeAccessoDestinazioniSocialiDestinazione() {
        return new ServiziType.Accesso.DestinazioniSociali.Destinazione();
    }

    /**
     * Create an instance of {@link PatrimonioType.Materiali }
     * 
     */
    public PatrimonioType.Materiali createPatrimonioTypeMateriali() {
        return new PatrimonioType.Materiali();
    }

    /**
     * Create an instance of {@link AmministrativaType.Strutture }
     * 
     */
    public AmministrativaType.Strutture createAmministrativaTypeStrutture() {
        return new AmministrativaType.Strutture();
    }

    /**
     * Create an instance of {@link ServiziType.InformazioniBibliografiche }
     * 
     */
    public ServiziType.InformazioniBibliografiche createServiziTypeInformazioniBibliografiche() {
        return new ServiziType.InformazioniBibliografiche();
    }

    /**
     * Create an instance of {@link SpecializzazioneType }
     * 
     */
    public SpecializzazioneType createSpecializzazioneType() {
        return new SpecializzazioneType();
    }

    /**
     * Create an instance of {@link CataloghiType.CataloghiGenerali }
     * 
     */
    public CataloghiType.CataloghiGenerali createCataloghiTypeCataloghiGenerali() {
        return new CataloghiType.CataloghiGenerali();
    }

    /**
     * Create an instance of {@link AmministrativaType.Ente }
     * 
     */
    public AmministrativaType.Ente createAmministrativaTypeEnte() {
        return new AmministrativaType.Ente();
    }

    /**
     * Create an instance of {@link AnagraficaType.Nomi }
     * 
     */
    public AnagraficaType.Nomi createAnagraficaTypeNomi() {
        return new AnagraficaType.Nomi();
    }

    /**
     * Create an instance of {@link ServiziType }
     * 
     */
    public ServiziType createServiziType() {
        return new ServiziType();
    }

    /**
     * Create an instance of {@link ServiziType.Riproduzioni.Riproduzione }
     * 
     */
    public ServiziType.Riproduzioni.Riproduzione createServiziTypeRiproduzioniRiproduzione() {
        return new ServiziType.Riproduzioni.Riproduzione();
    }

    /**
     * Create an instance of {@link AmministrativaType.Strutture.Superficie }
     * 
     */
    public AmministrativaType.Strutture.Superficie createAmministrativaTypeStruttureSuperficie() {
        return new AmministrativaType.Strutture.Superficie();
    }

    /**
     * Create an instance of {@link CatalogoCollettivoType }
     * 
     */
    public CatalogoCollettivoType createCatalogoCollettivoType() {
        return new CatalogoCollettivoType();
    }

    /**
     * Create an instance of {@link CatalogoType.Copertura }
     * 
     */
    public CatalogoType.Copertura createCatalogoTypeCopertura() {
        return new CatalogoType.Copertura();
    }

    /**
     * Create an instance of {@link AnagraficaType.Fonte }
     * 
     */
    public AnagraficaType.Fonte createAnagraficaTypeFonte() {
        return new AnagraficaType.Fonte();
    }

    /**
     * Create an instance of {@link ServiziType.Prestito.Interbibliotecario.TipoPrestito }
     * 
     */
    public ServiziType.Prestito.Interbibliotecario.TipoPrestito createServiziTypePrestitoInterbibliotecarioTipoPrestito() {
        return new ServiziType.Prestito.Interbibliotecario.TipoPrestito();
    }

    /**
     * Create an instance of {@link MaterialeType }
     * 
     */
    public MaterialeType createMaterialeType() {
        return new MaterialeType();
    }

    /**
     * Create an instance of {@link ServiziType.Accesso }
     * 
     */
    public ServiziType.Accesso createServiziTypeAccesso() {
        return new ServiziType.Accesso();
    }

    /**
     * Create an instance of {@link AmministrativaType.Strutture.Scaffalature }
     * 
     */
    public AmministrativaType.Strutture.Scaffalature createAmministrativaTypeStruttureScaffalature() {
        return new AmministrativaType.Strutture.Scaffalature();
    }

    /**
     * Create an instance of {@link AmministrativaType.Bilancio.Uscite }
     * 
     */
    public AmministrativaType.Bilancio.Uscite createAmministrativaTypeBilancioUscite() {
        return new AmministrativaType.Bilancio.Uscite();
    }

    /**
     * Create an instance of {@link ServiziType.Prestito.Interbibliotecario.SistemaIll }
     * 
     */
    public ServiziType.Prestito.Interbibliotecario.SistemaIll createServiziTypePrestitoInterbibliotecarioSistemaIll() {
        return new ServiziType.Prestito.Interbibliotecario.SistemaIll();
    }

    /**
     * Create an instance of {@link AnagraficaType.Edificio }
     * 
     */
    public AnagraficaType.Edificio createAnagraficaTypeEdificio() {
        return new AnagraficaType.Edificio();
    }

    /**
     * Create an instance of {@link ServiziType.Orario.Chiusura }
     * 
     */
    public ServiziType.Orario.Chiusura createServiziTypeOrarioChiusura() {
        return new ServiziType.Orario.Chiusura();
    }

    /**
     * Create an instance of {@link AnagraficaType.Contatti.Altri }
     * 
     */
    public AnagraficaType.Contatti.Altri createAnagraficaTypeContattiAltri() {
        return new AnagraficaType.Contatti.Altri();
    }

    /**
     * Create an instance of {@link AnagraficaType.Indirizzo.Coordinate }
     * 
     */
    public AnagraficaType.Indirizzo.Coordinate createAnagraficaTypeIndirizzoCoordinate() {
        return new AnagraficaType.Indirizzo.Coordinate();
    }

    /**
     * Create an instance of {@link AnagraficaType.Nomi.Precedenti }
     * 
     */
    public AnagraficaType.Nomi.Precedenti createAnagraficaTypeNomiPrecedenti() {
        return new AnagraficaType.Nomi.Precedenti();
    }

    /**
     * Create an instance of {@link MaterialeCataloghiType.Forme }
     * 
     */
    public MaterialeCataloghiType.Forme createMaterialeCataloghiTypeForme() {
        return new MaterialeCataloghiType.Forme();
    }

    /**
     * Create an instance of {@link Biblioteche }
     * 
     */
    public Biblioteche createBiblioteche() {
        return new Biblioteche();
    }

    /**
     * Create an instance of {@link AmministrativaType.CartaServizi }
     * 
     */
    public AmministrativaType.CartaServizi createAmministrativaTypeCartaServizi() {
        return new AmministrativaType.CartaServizi();
    }

    /**
     * Create an instance of {@link PatrimonioType.FondiSpeciali }
     * 
     */
    public PatrimonioType.FondiSpeciali createPatrimonioTypeFondiSpeciali() {
        return new PatrimonioType.FondiSpeciali();
    }

    /**
     * Create an instance of {@link CatalogoSpecialeType }
     * 
     */
    public CatalogoSpecialeType createCatalogoSpecialeType() {
        return new CatalogoSpecialeType();
    }

    /**
     * Create an instance of {@link DigitaleType }
     * 
     */
    public DigitaleType createDigitaleType() {
        return new DigitaleType();
    }

    /**
     * Create an instance of {@link CatalogoSpecialeType.Materiali }
     * 
     */
    public CatalogoSpecialeType.Materiali createCatalogoSpecialeTypeMateriali() {
        return new CatalogoSpecialeType.Materiali();
    }

    /**
     * Create an instance of {@link ServiziType.InformazioniBibliografiche.ServizioEsterno }
     * 
     */
    public ServiziType.InformazioniBibliografiche.ServizioEsterno createServiziTypeInformazioniBibliograficheServizioEsterno() {
        return new ServiziType.InformazioniBibliografiche.ServizioEsterno();
    }

    /**
     * Create an instance of {@link FormaType }
     * 
     */
    public FormaType createFormaType() {
        return new FormaType();
    }

    /**
     * Create an instance of {@link AnagraficaType.Istituzione }
     * 
     */
    public AnagraficaType.Istituzione createAnagraficaTypeIstituzione() {
        return new AnagraficaType.Istituzione();
    }

    /**
     * Create an instance of {@link ServiziType.Reference }
     * 
     */
    public ServiziType.Reference createServiziTypeReference() {
        return new ServiziType.Reference();
    }

    /**
     * Create an instance of {@link ServiziType.Prestito }
     * 
     */
    public ServiziType.Prestito createServiziTypePrestito() {
        return new ServiziType.Prestito();
    }

    /**
     * Create an instance of {@link ServiziType.DocumentDelivery }
     * 
     */
    public ServiziType.DocumentDelivery createServiziTypeDocumentDelivery() {
        return new ServiziType.DocumentDelivery();
    }

    /**
     * Create an instance of {@link ServiziType.DocumentDelivery.Forme }
     * 
     */
    public ServiziType.DocumentDelivery.Forme createServiziTypeDocumentDeliveryForme() {
        return new ServiziType.DocumentDelivery.Forme();
    }

}
