//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.04 at 12:16:10 PM CEST 
//


package xml.xsd.v16;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Anche l'elemento "fondo-speciale" va ripetuto per
 * 				ciascuna istanza di fondo. Inventario e catalogo
 * 				topografico sono
 * 				invece non ripetibili. L'elemento
 * 				"fondi-antichi", invece, serve solo
 * 				a conteggiare in
 * 				modo approssimativo i volumi dei diversi fondi
 * 				antichi
 * 				della biblioteca, e quindi non è ripetibile. I tre
 * 				valori
 * 				dell'attributo "volumi" sono da intendersi "fino
 * 				a 1000", "da 1000 a
 * 				5000", e "oltre 5000".
 * 			
 * 
 * <p>Java class for patrimonioType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="patrimonioType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="materiali" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="materiale" type="{}materialeType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fondi-speciali" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fondo-speciale" type="{}fondoSpecialeType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fondi-antichi" type="{}fondoAnticoType" minOccurs="0"/>
 *         &lt;element name="inventario" type="{}infCarType" minOccurs="0"/>
 *         &lt;element name="catalogo-topografico" type="{}infCarType" minOccurs="0"/>
 *         &lt;element name="acquisti-ultimi-quindici-anni" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="totale-posseduto" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="totale-posseduto-ragazzi" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "patrimonioType", propOrder = {
    "materiali",
    "fondiSpeciali",
    "fondiAntichi",
    "inventario",
    "catalogoTopografico",
    "acquistiUltimiQuindiciAnni",
    "totalePosseduto",
    "totalePossedutoRagazzi"
})
public class PatrimonioType {

    protected PatrimonioType.Materiali materiali;
    @XmlElement(name = "fondi-speciali")
    protected PatrimonioType.FondiSpeciali fondiSpeciali;
    @XmlElement(name = "fondi-antichi")
    protected FondoAnticoType fondiAntichi;
    protected InfCarType inventario;
    @XmlElement(name = "catalogo-topografico")
    protected InfCarType catalogoTopografico;
    @XmlElement(name = "acquisti-ultimi-quindici-anni")
    protected BigDecimal acquistiUltimiQuindiciAnni;
    @XmlElement(name = "totale-posseduto")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger totalePosseduto;
    @XmlElement(name = "totale-posseduto-ragazzi")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger totalePossedutoRagazzi;

    /**
     * Gets the value of the materiali property.
     * 
     * @return
     *     possible object is
     *     {@link PatrimonioType.Materiali }
     *     
     */
    public PatrimonioType.Materiali getMateriali() {
        return materiali;
    }

    /**
     * Sets the value of the materiali property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatrimonioType.Materiali }
     *     
     */
    public void setMateriali(PatrimonioType.Materiali value) {
        this.materiali = value;
    }

    /**
     * Gets the value of the fondiSpeciali property.
     * 
     * @return
     *     possible object is
     *     {@link PatrimonioType.FondiSpeciali }
     *     
     */
    public PatrimonioType.FondiSpeciali getFondiSpeciali() {
        return fondiSpeciali;
    }

    /**
     * Sets the value of the fondiSpeciali property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatrimonioType.FondiSpeciali }
     *     
     */
    public void setFondiSpeciali(PatrimonioType.FondiSpeciali value) {
        this.fondiSpeciali = value;
    }

    /**
     * Gets the value of the fondiAntichi property.
     * 
     * @return
     *     possible object is
     *     {@link FondoAnticoType }
     *     
     */
    public FondoAnticoType getFondiAntichi() {
        return fondiAntichi;
    }

    /**
     * Sets the value of the fondiAntichi property.
     * 
     * @param value
     *     allowed object is
     *     {@link FondoAnticoType }
     *     
     */
    public void setFondiAntichi(FondoAnticoType value) {
        this.fondiAntichi = value;
    }

    /**
     * Gets the value of the inventario property.
     * 
     * @return
     *     possible object is
     *     {@link InfCarType }
     *     
     */
    public InfCarType getInventario() {
        return inventario;
    }

    /**
     * Sets the value of the inventario property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfCarType }
     *     
     */
    public void setInventario(InfCarType value) {
        this.inventario = value;
    }

    /**
     * Gets the value of the catalogoTopografico property.
     * 
     * @return
     *     possible object is
     *     {@link InfCarType }
     *     
     */
    public InfCarType getCatalogoTopografico() {
        return catalogoTopografico;
    }

    /**
     * Sets the value of the catalogoTopografico property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfCarType }
     *     
     */
    public void setCatalogoTopografico(InfCarType value) {
        this.catalogoTopografico = value;
    }

    /**
     * Gets the value of the acquistiUltimiQuindiciAnni property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAcquistiUltimiQuindiciAnni() {
        return acquistiUltimiQuindiciAnni;
    }

    /**
     * Sets the value of the acquistiUltimiQuindiciAnni property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAcquistiUltimiQuindiciAnni(BigDecimal value) {
        this.acquistiUltimiQuindiciAnni = value;
    }

    /**
     * Gets the value of the totalePosseduto property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalePosseduto() {
        return totalePosseduto;
    }

    /**
     * Sets the value of the totalePosseduto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalePosseduto(BigInteger value) {
        this.totalePosseduto = value;
    }

    /**
     * Gets the value of the totalePossedutoRagazzi property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalePossedutoRagazzi() {
        return totalePossedutoRagazzi;
    }

    /**
     * Sets the value of the totalePossedutoRagazzi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalePossedutoRagazzi(BigInteger value) {
        this.totalePossedutoRagazzi = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fondo-speciale" type="{}fondoSpecialeType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fondoSpeciale"
    })
    public static class FondiSpeciali {

        @XmlElement(name = "fondo-speciale")
        protected List<FondoSpecialeType> fondoSpeciale;

        /**
         * Gets the value of the fondoSpeciale property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fondoSpeciale property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFondoSpeciale().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FondoSpecialeType }
         * 
         * 
         */
        public List<FondoSpecialeType> getFondoSpeciale() {
            if (fondoSpeciale == null) {
                fondoSpeciale = new ArrayList<FondoSpecialeType>();
            }
            return this.fondoSpeciale;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="materiale" type="{}materialeType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "materiale"
    })
    public static class Materiali {

        protected List<MaterialeType> materiale;

        /**
         * Gets the value of the materiale property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the materiale property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMateriale().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MaterialeType }
         * 
         * 
         */
        public List<MaterialeType> getMateriale() {
            if (materiale == null) {
                materiale = new ArrayList<MaterialeType>();
            }
            return this.materiale;
        }

    }

}
